modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Swordstone86/AstrologicalSorcery/issues"
[[mods]]
modId="astrosorc"
version="${file.jarVersion}"
displayName="Astrological Sorcery"
displayURL="https://www.curseforge.com/minecraft/mc-mods/astrological-sorcery"
logoFile="banner.png"
credits="HellFirePvP & wiiv for the awesome original Astral Sorcery mod. Astrological Sorcery logo background by freepik - www.freepik.com"
authors="Swordstone"
description='''Astral Sorcery but with zodiac constellations'''
[[dependencies.astrosorc]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.astrosorc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.astrosorc]]
    modId="astralsorcery"
    mandatory=true
    versionRange="[1.16.4-1.13.4,]"
    ordering="BEFORE"
    side="BOTH"